### ISSUE TITLE
Extension defaults error

### ISSUE THREAD

**Issue by martenb** [ondrs/upload-manager#11]
Hi,

default parameter of DI\extension [imageManager.dimensions](https://github.com/ondrs/upload-manager/blob/master/src/ondrs/UploadManager/DI/Extension.php#L27) should be empty array instead of NULL.

NULL value causes Recoverable Error with "Minimal configuration"...

**Comment by ondrs** [comment]
Can you please create a pull request with the fix? I am not quite sure what do you mean.

**Comment by martenb** [comment]
Sorry, but no. I finaly choosed another library. This was too complex for my purposes.
