### ISSUE TITLE
upload .pdf nefunguje

### ISSUE THREAD

**Issue by JVwebar** [ondrs/upload-manager#14]
Ahoj, nefunguje upload .pdf souborů a přijde mi, že blackList také nefunguje, je ve formě {php,phtml,html,css,js}, ale soubor s názvem index.html nahrát jde, ovšek .pdf nikoliv, hází hlášku "an error occured during file upload"

**Comment by ondrs** [comment]
Nejspise mas spatne nakonfigurovany server nebo spatne nadefinovanou extension v config.neon
Podivej se nejdrive tam.
