### ISSUE TITLE
PHP 7.2 - Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by ondrakub** [ondrs/upload-manager#15]
- bug report? yes
- feature request? no
- version: 6.0.2

Description

- PHP 7.2 uses "Object" as typehint (https://wiki.php.net/rfc/object-typehint).
- Tested with "php:7.2.0RC5".

**Comment by ondrs** [comment]
https://github.com/ondrs/upload-manager/releases/tag/v0.7
