### ISSUE TITLE
Release verze 7.0

### ISSUE THREAD

**Issue by marten-cz** [ondrs/upload-manager#18]
Predpokladam, ze posledni verze ma byt 7.0 a ne 0.7. Nebo jsou spatne verze 6.0.*
Pripadne jestli by slo releasnout i aktualni kod.

**Comment by ondrs** [comment]
Hm no evidentne jsem 0.6 vydal spatne jako 6 :)
Tak ted uz asi vydam rovnou 7.0, aby se nic nerozbilo? :)
