### ISSUE TITLE
Moznost vypnout ImageManager

### ISSUE THREAD

**Issue by marten-cz** [ondrs/upload-manager#3]
Ne vzdycky chci specialne resit soubory. Napriklad se k nim chovam stejne jako k ostatnim souborum, nebo jejich resize resim jinak. Ted lze obejit pres

```
$this->uploadManager->setImageManager($this->uploadManager->getFileManager());
```

S typehintem na constructu to nelze lehce obejit. Bylo by dobre mit hlavni filemanager a moznost pridat dalsi podle mimetype. Dokazu si predstavit specialni manager pro video, audio, pdf,...

**Comment by ondrs** [comment]
Popřemýšlím nad tím. Současné řešení je dost lightweight. 
Potřebuji implementovat i nějaký storage/saver interface pro zápis do různých uložišt např. S3. 
ImageManager musí být taky trochu chytřejší, aby mohl provádět více transformací
a využívat jinou knihovnu než GD, např GraphicsMagick nebo ImageMagick
